//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_MVC_HOMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class 客戶聯絡人
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "必填")]
        public int 客戶Id { get; set; }

        [Required(ErrorMessage = "必填")]
        [MaxLength(50)]
        public string 職稱 { get; set; }

        [Required(ErrorMessage = "必填")]
        [MaxLength(50)]
        public string 姓名 { get; set; }

        [MaxLength(250)]
        [Required(ErrorMessage = "必填")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Email格式錯誤")]
        [Remote("CheckCustomContactEmail", "Validate", ErrorMessage = "Email已存在")]
        public string Email { get; set; }

        [MaxLength(50)]
        [RegularExpression(@"\d{4}-\d{6}", ErrorMessage = "手機格式錯誤")]
        public string 手機 { get; set; }

        [MaxLength(50)]
        public string 電話 { get; set; }


        public bool fbDELETE { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
